// Generated by typings
// Source: https://raw.githubusercontent.com/Aurelia/Fetch-client/master/doc/url.d.ts
declare class URLSearchParams {
	append(name: string, value: string): void;
	delete(name: string):void;
	get(name: string): string;
	getAll(name: string): Array<string>;
	has(name: string): boolean;
	set(name: string, value: string): void;
}
